### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by dromer**
Couldn't really open an issue on your repository, but I wanted to let you know that I've already implemented python3 support in my fork.

### CODE REVIEW

**Comment by rhaleblian** [comment]
Thanks for mentioning that.  Right now that's the only reason this fork exists, so i'll try to use your fork if you think that works for you.  I can then whack this fork.
Speaking more broadly, i'd like to know who is doing what to this codebase, as i'm wondering about its future life.
I'd propose a meet-and-greet with active developers.

**Comment by rhaleblian** [comment]
Of course, if everybody is in the loop i'll just try to get into that loop.

**Comment by dromer** [comment]
I have no idea who is "in the loop". It seems everyone is doing their own fork, but I've tried to implement most of the other forks' work + add basic PEP8 tests, replaced the VST2 implementation with DPF output (bit of a WIP), and made it a python package that you can install from pypi.

Of course I (try to) accept pull requests :)

By the way I'm quite active in #lad and #dataflow on irc.freenode.net if you want a chat

**Comment by rhaleblian** [comment]
All the enhancements you mention sound good.
I'll drop into those chats.
I was doing mods to support a community of guitarists who create stomp boxes with Electrosmith Daisy.

**Comment by rhaleblian** [comment]
I'm relying on the changes on `electro-smith`s fork (https://github.com/stephenhensley/hvcc) that add support the Daisy, so i can't use this directly.  It may be plausible to incorporate those changes into this.  I may be able to get some idea from them what their plan and stance are.

**Comment by dromer** [comment]
That fork doesn't have anything not in enzienaudio already (it's 2 commits behind), so which changes are you looking for?

Definitely interested to integrate as many fixes and extensions as we can, no point in this fragmentation of forks.

**Comment by dromer** [comment]
Ah, do you mean https://github.com/electro-smith/pd2dsy ?

**Comment by dromer** [comment]
> Ah, do you mean https://github.com/electro-smith/pd2dsy ?

I think the only thing you'd need to edit is https://github.com/electro-smith/pd2dsy/blob/master/pd2dsy.py#L123
And even then you can use this flag to override this with just `-c hvcc` and you should be done.

**Comment by rhaleblian** [comment]
Yep, pd2dsy is the wrapper.  It uses the `hvcc` cited above (see submodule def), which i now see was forked from @pingdynasty .

**Comment by dromer** [comment]
@rhaleblian btw, we support Daisy now in the v0.2.0 version of hvcc (`pip3 install -U hvcc`) -> https://github.com/Wasted-Audio/hvcc/releases/tag/v0.2.0

Coming months we'll work to adapt to their new, diy friendly, board configuration format.

**Pull request merged**
